### PR TITLE
Kinyarwanda hymn

### PR DESCRIPTION
**Pull request by Burkifa23**
Hello @TinasheMzondiwa,
This is just a sample before I continue 345+ songs. Does the kinyarwanda.json markdown conform to the app's requirement? If not, what can I change?

### CODE REVIEW

**Comment by TinasheMzondiwa** [comment]
This is perfect 🙌🏾

**Comment by Burkifa23** [comment]
ok  I'll continue

**Comment by TinasheMzondiwa** [comment]
Thank you @Burkifa23 
We currently don't have a way to preview but I'll test these in the Android app and merge the PR

**Comment by TinasheMzondiwa** [comment]
@Burkifa23 I've edited the json file with these changes:
1. Changed `content` to `markdown`
2. Removed extra empty lines
3. Formatted first hymn - See difference in below screenshots of the changes

| Before                       | After                       |
| ----------------------------- | ---------------------------- |
| Before  | After

**Comment by Burkifa23** [comment]
Thank you so much, I will then update the format for the rest. Is it possible to control paragraphs by adding "\n" to make it look like this
### 1 Murinzi We , Vuz' Impanda 
**1.**
Murinzi, jy' uvuz' impanda, Uhan' umuntu wese; 
Ng' uzumv' izo nkuru nziza,  Yihan' akiz' ibyaha.


 **GUSUBURIMO:**
Murinzi we vuz' impanda! Yivuze cyane hose (hose),  
Menyesha bos' ubutumwa,  Imbohe zibohorwe.

And so on...

**Comment by Burkifa23** [comment]
Greetings @TinasheMzondiwa ,
I hope you are doing well. Check if the changes I've made are correct.

**Comment by TinasheMzondiwa** [comment]
@Burkifa23 I've formatted the file again.

- Please check hymn `51` and hymn `246` I think some words are missing there.

- If you can check these two then we can merge.

We can do this in a follow-up PR
> Is it possible to control paragraphs by adding "\n"

**Review by TinasheMzondiwa — APPROVED** [review]
Thank you!

**Comment by TinasheMzondiwa** [comment]
Closes #9

**Comment by danielbyiringiro** [comment]
l think it has to be "Gusubiramo" for the chorus part instead of "Gusubirimo"; cause "Gusibiramo" is the Kinyarwandan word used for repeating.

**Comment by Burkifa23** [comment]
> l think it has to be "Gusubiramo" for the chorus part instead of "Gusubirimo"; cause "Gusibiramo" is the Kinyarwandan word used for repeating.

Thank @danielbyiringiro for spotting that typo. I'll make the necessary changes.

**Pull request merged**
